version: '3.7'
services:
  caddy:
    build:
      context: .
      dockerfile: ./compose/production/caddy/Dockerfile
    image: registry.gitlab.com/multy/multy_herr/caddy:prod
    depends_on:
      - candybot
    volumes:
      - production_caddy:/root/.caddy
    env_file:
      - ./.envs/.production/.caddy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  candybot:
    build:
      context: .
      dockerfile: DockerFile
    depends_on:
      - action_server
    ports:
      - "5005:5005"
    command: >
      bash -c "make train-nlu
      && make train-core
      && make run-core"

  action_server:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "5055:5055"
    command: ["make", "run-actions"]

volumes:
  production_caddy: {}