variables:
  PYENV_ROOT: "$HOME/.pyenv"
  PATH: "/home/gitlab-runner/.pyenv/shims:/home/gitlab-runner/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
  PIPENV_PYTHON: "$PYENV_ROOT/shims/python"

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - candybot
  script:
    - python -V
    - ls -alh
    - pwd
    - whoami
    - cd candybot
    - docker-compose build

deploy:
  stage: deploy
  tags:
    - candybot
    - rasa
  script:
    - cd candybot
    - docker-compose down
    - docker-compose up